import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.Timer; // Important for safe removal while iterating

/**
 * The main game panel where all game objects are drawn and updated.
 * Manages the game loop, object spawning, and collision detection.
 */
public class GamePanel extends JPanel implements ActionListener {

    // Public static final constants for screen dimensions, accessible by other classes
    public static final int SCREEN_WIDTH = 800;
    public static final int SCREEN_HEIGHT = 600;

    private Player player;
    private GameOverText gameOver;
    private ArrayList<GameObject> gameObjects; // The key ArrayList for polymorphism!
    private Timer gameLoopTimer; // Controls the game's frame rate

    private long lastEnemySpawnTime = 0;
    private final long ENEMY_SPAWN_DELAY = 1000; // milliseconds between enemy spawns
    
    private long lastPowerUpSpawnTime = 0;
    private final long POWER_UP_SPAWN_DELAY = 3000;
    
    private int score;

    /**
     * Constructor for GamePanel.
     * Sets up the panel, initializes game objects, and starts the game loop.
     */
    public GamePanel() {
        setPreferredSize(new Dimension(SCREEN_WIDTH, SCREEN_HEIGHT));
        setBackground(Color.BLACK); // Black background for space theme
        setFocusable(true); // JPanel must be focusable to receive keyboard input

        // Initialize game objects
        // Player is positioned at the bottom center
        player = new Player(SCREEN_WIDTH / 2 - 25, SCREEN_HEIGHT - 70, 50, 50, 5);
        gameObjects = new ArrayList<>();
        gameObjects.add(player); // Add the player to the list of all game objects
        
        gameOver = new GameOverText(250, 300, 50, 50);

        // Add key listener for player input
        addKeyListener(new GameKeyListener());

        // Setup game loop timer (e.g., 60 frames per second)
        // The Timer calls actionPerformed() repeatedly
        gameLoopTimer = new Timer(1000 / 60, this); // 1000ms / 60 = ~16ms per frame
        gameLoopTimer.start(); // Start the game loop
        
        score = 0;
    }

    /**
     * Called automatically by Swing to paint the component.
     * Iterates through all active game objects and calls their draw() method.
     * @param g The Graphics object used for drawing.
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Clear the panel
        // Iterate through all game objects and draw them polymorphically
        for (GameObject obj : gameObjects) {
            if (obj.isActive()) { // Only draw active objects
                obj.draw(g);
            }
        }
        g.setColor(Color.WHITE);
        g.drawString("Score: " + score + "     Lives: " + player.getLives(), 2, 11);
        gameOver.draw(g);
    }

    /**
     * This method is called repeatedly by the gameLoopTimer.
     * It contains the core game logic for updating object states, spawning, and collisions.
     * @param e The ActionEvent generated by the Timer.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        // 1. Update all game objects
        // Use an Iterator for safe removal of objects while iterating
        Iterator<GameObject> iterator = gameObjects.iterator();
        while (iterator.hasNext()) {
            GameObject obj = iterator.next();
            obj.update(); // Call the specific update method for each object type
            if (!obj.isActive()) {
                iterator.remove(); // Remove inactive objects (e.g., off-screen enemies/projectiles)
            }
        }

        // 2a. Spawn new enemies
        long currentTime = System.currentTimeMillis();
        if (currentTime - lastEnemySpawnTime > ENEMY_SPAWN_DELAY) {
            // Spawn enemy at a random x-position at the top of the screen
            int enemyType = (int) (Math.random() * 3);
            
            if (enemyType == 0) {
                int enemyX = (int) (Math.random() * (SCREEN_WIDTH - 40)); // 40 is enemy width
                gameObjects.add(new Enemy(enemyX, 0, 40, 40, 2)); // Add new enemy to the list
                lastEnemySpawnTime = currentTime;
            }
            else if (enemyType == 1) {
                int enemyX = (int) (Math.random() * (SCREEN_WIDTH - 40)); // 40 is enemy width
                gameObjects.add(new FastEnemy(enemyX, 0, 40, 40, 4)); // Add new enemy to the list
                lastEnemySpawnTime = currentTime;
            }
            else {
                int enemyX = (int) (Math.random() * (SCREEN_WIDTH - 40)); // 40 is enemy width
                gameObjects.add(new BigEnemy(enemyX, 0, 40, 40, 1, 5)); // Add new enemy to the list
                lastEnemySpawnTime = currentTime;
            }
        }
        
        // 2b. Spawn new power ups
        long powerUpTime = System.currentTimeMillis();
        if (powerUpTime - lastPowerUpSpawnTime > POWER_UP_SPAWN_DELAY) {
            // Spawn enemy at a random x-position at the top of the screen
            int powerUpType = (int) (Math.random() * 2);
            
            if (powerUpType == 0) {
                int powerUpX = (int) (Math.random() * (SCREEN_WIDTH - 30)); // 30 is power up width
                gameObjects.add(new PlayerSpeedPowerUp(powerUpX, 0, 30, 30, 5)); // Add new power up to the list
                lastPowerUpSpawnTime = powerUpTime;
            }
            else {
                int powerUpX = (int) (Math.random() * (SCREEN_WIDTH - 30)); // 30 is power up width
                gameObjects.add(new ProjectileSizePowerUp(powerUpX, 0, 30, 30, 5)); // Add new power up to the list
                lastPowerUpSpawnTime = powerUpTime;
            }
        }

        // 3a. Handle Collisions (Projectile and Enemy)
        // Iterate through projectiles and enemies to check for collisions
        // Create copies of the list to avoid ConcurrentModificationException when removing
        ArrayList<GameObject> currentObjects = new ArrayList<>(gameObjects);
        for (GameObject proj : currentObjects) {
            if (proj instanceof Projectile && proj.isActive()) { // Check if it's an active projectile
                for (GameObject enemy : currentObjects) {
                    if (enemy instanceof Enemy && enemy.isActive()) { // Check if it's an active enemy
                        // Check for intersection of their bounding boxes
                        if (enemy instanceof BigEnemy && proj.getBounds().intersects(enemy.getBounds())) {
                            proj.setActive(false);
                            BigEnemy theEnemy = (BigEnemy) enemy;
                            theEnemy.setHealth(theEnemy.getHealth() - 1);
                            
                            if (theEnemy.getHealth() <= 0) {
                                theEnemy.setActive(false);
                                score += 5;
                            }
                        }
                        else if (proj.getBounds().intersects(enemy.getBounds())) {
                            // Collision detected!
                            proj.setActive(false); // Deactivate projectile
                            enemy.setActive(false); // Deactivate enemy
                            if (enemy instanceof FastEnemy) {
                                score += 3;
                            }
                            else {
                                score += 1;
                            }
                        }
                    }
                }
            }
        }
        
        // 3b. Handle Collisions (Player and Enemy)
        // Iterate through enemies to check for collisions with player
        // Creates copy of the list to avoid ConcurrentModificationException when removing
        ArrayList<GameObject> enemyObjects = new ArrayList<>(gameObjects);
        for (GameObject enemy : enemyObjects) {
            if (enemy instanceof Enemy && enemy.isActive()) {
                if (enemy.getBounds().intersects(player.getBounds())) {
                    enemy.setActive(false);
                    player.decreaseLives();
                    if (player.getLives() <= 0) {
                        gameLoopTimer.stop();
                        
                        for (GameObject object : gameObjects) {
                            object.setActive(false);
                        }
                        
                        gameOver.setActive(true);
                    }
                }
            }
        }
        
        // 3c. Handle Collisions (Player and PowerUp)
        // Iterate through enemies to check for collisions with player
        // Creates copy of the list to avoid ConcurrentModificationException when removing
        ArrayList<GameObject> powerUpObjects = new ArrayList<>(gameObjects);
        for (GameObject powerUp : powerUpObjects) {
            if (powerUp instanceof PlayerSpeedPowerUp && powerUp.isActive()) {
                if (powerUp.getBounds().intersects(player.getBounds())) {
                    powerUp.setActive(false);
                    player.setSpeed(player.getSpeed() + 1);
                }
            }
            else if (powerUp instanceof ProjectileSizePowerUp && powerUp.isActive()) {
                if (powerUp.getBounds().intersects(player.getBounds())) {
                    powerUp.setActive(false);
                    ProjectileSizePowerUp.increaseSize();
                }
            }
        }

        // 4. Repaint the panel to show updated positions and new objects
        repaint();
    }

    /**
     * Inner class to handle keyboard input for the game.
     * Extends KeyAdapter to only override necessary methods.
     */
    private class GameKeyListener extends KeyAdapter {
        /**
         * Called when a key is pressed.
         * Controls player movement and shooting.
         * @param e The KeyEvent generated by the key press.
         */
        @Override
        public void keyPressed(KeyEvent e) {
            player.keyPressed(e.getKeyCode()); // Delegate movement to Player class
            if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                // When space is pressed, create a new Projectile
                // Position the projectile at the center of the player's top edge
                Projectile p = new Projectile(player.getX() + player.getWidth() / 2 - 5,
                                              player.getY(), 10 + ProjectileSizePowerUp.getSizeInc(), 20 + ProjectileSizePowerUp.getSizeInc(), 10);
                gameObjects.add(p); // Add the new projectile to the game objects list
            }
        }

        /**
         * Called when a key is released.
         * Stops player movement when movement keys are released.
         * @param e The KeyEvent generated by the key release.
         */
        @Override
        public void keyReleased(KeyEvent e) {
            player.keyReleased(e.getKeyCode()); // Delegate stopping movement to Player class
        }
    }
}